let rope_insert pos ins_str rope = Utf8_rope.insert pos ins_str rope
let rope_delete start length rope = Utf8_rope.delete start length rope
let rope_to_string rope = Utf8_rope.to_string rope

let svelte =
  Utils.run_txns_time "Svelete Rope" Sveltecomponent.data Utf8_rope.empty
    rope_insert rope_delete

(* let svelte_error = *)
(* Utf8_rope.N2 *)
(*  {Utf8_rope. = *)
(*    Utf8_rope.N2 *)
(*     {Utf8_rope.l = *)
(*       Utf8_rope.N2 *)
(*        {Utf8_rope.l = *)
(*          Utf8_rope.N2 *)
(*           {Utf8_rope.l = *)
(*             Utf8_rope.N2 *)
(*              {Utf8_rope.l = *)
(*                Utf8_rope.N0 {Brolib.Utf8_rope.str = ""; lines = [||]}; *)
(*               lm = 0; lm_lines = 0; rm = 0; rm_lines = 0; *)
(*               r = Utf8_rope.N0 {Brolib.Utf8_rope.str = ""; lines = [||]}}; *)
(*            lm = 0; lm_lines = 0; rm = 0; rm_lines = 0; *)
(*            r = *)
(*             Utf8_rope.N1 *)
(*              (Utf8_rope.N0 {Brolib.Utf8_rope.str = ""; lines = [||]})}; *)
(*         lm = 0; lm_lines = 0; rm = 0; rm_lines = 0; *)
(*         r = *)
(*          Utf8_rope.N1 *)
(*           (Utf8_rope.N2 *)
(*             {Utf8_rope.l = *)
(*               Utf8_rope.N0 {Brolib.Utf8_rope.str = ""; lines = [||]}; *)
(*              lm = 0; lm_lines = 0; rm = 0; rm_lines = 0; *)
(*              r = Utf8_rope.N0 {Brolib.Utf8_rope.str = ""; lines = [||]}})}; *)
(*      lm = 0; lm_lines = 0; rm = 0; rm_lines = 0; *)
(*      r = *)
(*       Utf8_rope.N1 *)
(*        (Utf8_rope.N2 *)
(*          {Utf8_rope.l = *)
(*            Utf8_rope.N2 *)
(*             {Utf8_rope.l = *)
(*               Utf8_rope.N0 {Brolib.Utf8_rope.str = ""; lines = [||]}; *)
(*              lm = 0; lm_lines = 0; rm = 0; rm_lines = 0; *)
(*              r = Utf8_rope.N0 {Brolib.Utf8_rope.str = ""; lines = [||]}}; *)
(*           lm = 0; lm_lines = 0; rm = 0; rm_lines = 0; *)
(*           r = *)
(*            Utf8_rope.N1 *)
(*             (Utf8_rope.N0 {Brolib.Utf8_rope.str = ""; lines = [||]})})}; *)
(*   lm = 0; lm_lines = 0; rm = 454; rm_lines = 30; *)
(*   r = *)
(*    Utf8_rope.N1 *)
(*     (Utf8_rope.N2 *)
(*       {Utf8_rope.l = *)
(*         Utf8_rope.N2 *)
(*          {Utf8_rope.l = *)
(*            Utf8_rope.N2 *)
(*             {Utf8_rope.l = *)
(*               Utf8_rope.N0 {Brolib.Utf8_rope.str = ""; lines = [||]}; *)
(*              lm = 0; lm_lines = 0; rm = 0; rm_lines = 0; *)
(*              r = Utf8_rope.N0 {Brolib.Utf8_rope.str = ""; lines = [||]}}; *)
(*           lm = 0; lm_lines = 0; rm = 0; rm_lines = 0; *)
(*           r = *)
(*            Utf8_rope.N2 *)
(*             {Utf8_rope.l = *)
(*               Utf8_rope.N0 {Brolib.Utf8_rope.str = ""; lines = [||]}; *)
(*              lm = 0; lm_lines = 0; rm = 0; rm_lines = 0; *)
(*              r = Utf8_rope.N0 {Brolib.Utf8_rope.str = ""; lines = [||]}}}; *)
(*        lm = 0; lm_lines = 0; rm = 454; rm_lines = 30; *)
(*        r = *)
(*         Utf8_rope.N2 *)
(*          {Utf8_rope.l = *)
(*            Utf8_rope.N1 *)
(*             (Utf8_rope.N0 {Brolib.Utf8_rope.str = ""; lines = [||]}); *)
(*           lm = 0; lm_lines = 0; rm = 454; rm_lines = 30; *)
(*           r = *)
(*            Utf8_rope.N2 *)
(*             {Utf8_rope.l = *)
(*               Utf8_rope.N0 {Brolib.Utf8_rope.str = ""; lines = [||]}; *)
(*              lm = 0; lm_lines = 0; rm = 454; rm_lines = 30; *)
(*              r = *)
(*               Utf8_rope.N0 *)
(*                {Utf8_rope.str = *)
(*                  "<script>\n\texport et name;\n\t\n</script>\n\n<main>\n\t<h1>Hello {name}!</h1>\n\t<p>Visit the <a href=\"https://svelte.dev/tutorial\">Svelte tutorial</a> to learn how to build Svelte apps.</p>"; *)
(*                 lines = *)
(*                  [|7; 25; 27; 37; 38; 45; 69; 180; 188; 189; 197; 205; 227; *)
(*                    243; 263; 281; 284; 285; 291; 309; 338; 356; 376; 379; 380; *)
(*                    409; 418; 438; 442; 445|]}}}})} *)
